import { VectorFeature, Layer, GeoTransform } from '../../types/cad';
import { pixelToMap } from '../georeference';

export function generateKML(
  features: VectorFeature[],
  layers: Layer[],
  geoTransform: GeoTransform
): string {
  const layerMap = new Map<string, Layer>();
  layers.forEach(l => layerMap.set(l.id, l));

  // Helper to convert hex #RRGGBB to KML aabbggrr
  const hexToKmlColor = (hex: string, alpha = 'cc') => {
    const clean = hex.replace('#', '');
    if (clean.length === 6) {
      const r = clean.substring(0, 2);
      const g = clean.substring(2, 4);
      const b = clean.substring(4, 6);
      return `${alpha}${b}${g}${r}`;
    }
    return `${alpha}ffffff`;
  };

  const styleTags = layers.map(l => {
    const lineCol = hexToKmlColor(l.color, 'ff');
    const polyCol = hexToKmlColor(l.color, '77');
    return `
    <Style id="style_${l.id}">
      <LineStyle>
        <color>${lineCol}</color>
        <width>${Math.max(1, Math.round(l.lineweight * 4))}</width>
      </LineStyle>
      <PolyStyle>
        <color>${polyCol}</color>
        <fill>1</fill>
        <outline>1</outline>
      </PolyStyle>
    </Style>`;
  }).join('\n');

  const placemarks = features.map(feat => {
    const layer = layerMap.get(feat.layerId) || layers[0];
    const coordsStr = feat.points.map(pt => {
      if (geoTransform.isCalibrated) {
        const mapPt = pixelToMap(pt, geoTransform);
        return `${mapPt.x.toFixed(6)},${mapPt.y.toFixed(6)},0`;
      }
      return `${pt.x.toFixed(2)},${pt.y.toFixed(2)},0`;
    }).join(' ');

    let geomXml = '';
    if (feat.closed && feat.points.length >= 3) {
      const first = feat.points[0];
      const last = feat.points[feat.points.length - 1];
      const closedCoordsStr = (first.x !== last.x || first.y !== last.y)
        ? `${coordsStr} ${coordsStr.split(' ')[0]}`
        : coordsStr;

      geomXml = `
      <Polygon>
        <extrude>1</extrude>
        <altitudeMode>relativeToGround</altitudeMode>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>${closedCoordsStr}</coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>`;
    } else {
      geomXml = `
      <LineString>
        <extrude>1</extrude>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>${coordsStr}</coordinates>
      </LineString>`;
    }

    return `
    <Placemark>
      <name>${feat.name || 'Feature'}</name>
      <description><![CDATA[
        Layer: ${layer.name}<br/>
        Type: ${feat.type}<br/>
        Area: ${feat.properties.area_m2 || feat.properties.area_px || 0} m²
      ]]></description>
      <styleUrl>#style_${layer.id}</styleUrl>
      ${geomXml}
    </Placemark>`;
  }).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>GeoVector CAD Mobile Export</name>
    <description>Generated by GeoVector CAD Mobile Engine</description>
    ${styleTags}
    ${placemarks}
  </Document>
</kml>`;
}
